### ISSUE TITLE
Lazy loaded routes

### ISSUE THREAD

**Issue by hakimio** [Danevandy99/ngx-advanced-router#1]
How is the library supposed to work with lazy loaded routes:
```ts
const routes: Routes = [
    {
        path: 'main-menu',
        loadChildren: () => import('./pages/main-menu/main-menu.module').then(m => m.MainMenuPageModule)
    },
    // ...
];
```

**Comment by Danevandy99** [comment]
Hi @hakimio!
This would be a good addition to the README, but in the meantime here are some quick setup instructions:

To use this library with lazy loaded routes, you'll need to create another service that extends the `AdvancedRouteService`. You'll want to override the `parentPath` property in this service, and set the value to the path of the `loadChildren` route from your parent route service. [(Example)](https://github.com/Danevandy99/ngx-advanced-router/blob/main/src/app/modules/lazy-loaded/services/lazy-loaded-route.service.ts) Similar to how Angular's `RouterModule` has a `forChild` function that you use to register routes in a lazy loaded module, you'll use `AdvancedRouterModule.forChild(YourLazyLoadedRouteService)`. [(Example)](https://github.com/Danevandy99/ngx-advanced-router/blob/main/src/app/modules/lazy-loaded/lazy-loaded.module.ts)

Let me know if you have any more questions.
